# Generated by Django 3.2.7 on 2021-09-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('pool_type', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=5)),
                ('size', models.FloatField(null=True)),
            ],
        ),
    ]
