version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Paipayales
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  web:
    build: .

    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db